import type { Metadata } from "next";
import LegalLayout from "@/components/legal/LegalLayout";

export const metadata: Metadata = {
  title: "Data Policy · Hawktress · BuildHawk",
  description:
    "Hawktress data policy. Privacy Act 1988 (Cth) compliant. Issued by BuildHawk Pty Ltd.",
};

export default function DataPolicyPage() {
  return (
    <LegalLayout
      eyebrow="Hawktress · Privacy"
      title="Data Policy"
      version="v2.0"
      date="1 May 2026"
    >
      <h2>1. Purpose</h2>
      <p>
        This policy governs how BuildHawk Pty Ltd collects, stores, uses, and
        protects data submitted to or generated by the Hawktress platform across
        all seven lifecycle stages: Estimating, Pre-Construction Planning,
        Contract Administration, Project Execution, Practical Completion,
        Intelligence Layer and Reporting.
      </p>
      <p>
        It applies to all builders, trades and suppliers who access Hawktress
        under any subscription tier. BuildHawk is committed to handling all data
        with commercial integrity and confidentiality, in accordance with the{" "}
        <strong>Privacy Act 1988 (Cth)</strong> and the Australian Privacy
        Principles (APPs).
      </p>

      <h2>2. Data we collect</h2>
      <h3>2.1 Estimating and pre-construction data</h3>
      <ul>
        <li>
          Trade quotes, scope descriptions, labour and material costs, rate
          types and quote documents
        </li>
        <li>Feasibility cost models and preliminary budget figures</li>
        <li>Procurement strategy notes and trade lead time records</li>
      </ul>
      <h3>2.2 Contract administration and execution data</h3>
      <ul>
        <li>
          Variation claims, variation values, approval status and supporting
          documents
        </li>
        <li>
          Purchase order values, issued dates, completion dates and final
          invoiced amounts
        </li>
        <li>Committed costs, forecast final costs and programme dates</li>
        <li>Supplier delivery performance and invoice records</li>
      </ul>
      <h3>2.3 Reporting data</h3>
      <ul>
        <li>Project-level cost and margin data used in monthly director reports</li>
        <li>
          Company-level financial snapshot data including contracted revenue,
          committed costs and forecast figures
        </li>
        <li>Aged debtor and cash position data where provided by the builder</li>
      </ul>
      <h3>2.4 Profile data</h3>
      <ul>
        <li>Builder, trade and supplier contact information and business details</li>
        <li>Brand kit assets including logos, colours and fonts</li>
        <li>Subscription tier and engagement history</li>
      </ul>

      <h2>3. How we use your data</h2>
      <h3>3.1 Primary use</h3>
      <p>
        All data is used to deliver the subscribed Hawktress service across the
        relevant lifecycle stages. This includes generating estimates,
        pre-construction benchmarks, variation assessments, live cost tracking,
        completion reports and monthly director reports.
      </p>
      <h3>3.2 Anonymised benchmarking</h3>
      <p>
        Hawktress uses anonymised, aggregated cost data to generate regional
        market benchmarks. The following rules apply without exception:
      </p>
      <ul>
        <li>The source of any pricing data is never disclosed to any party</li>
        <li>
          Regional benchmarks show market-level pricing only, never
          project-specific or builder-specific figures
        </li>
        <li>
          No data submitted by any subscriber is attributed to that party in any
          output visible to another subscriber
        </li>
        <li>Supplier names are never disclosed in benchmark outputs</li>
      </ul>
      <h3>3.3 Variation threshold enforcement</h3>
      <p>
        Variation and quote data is used by Hawktress to enforce the 5%
        variance threshold. When a variation or quote exceeds this threshold,
        the relevant record is flagged automatically. This flag is visible
        internally to BuildHawk and the relevant builder's CA. It is not shared
        with any other subscriber.
      </p>

      <h2>4. Data storage</h2>
      <p>
        Hawktress data is stored in GoHighLevel. Platform hosting arrangements are
        subject to confirmation and will be communicated to subscribers when
        finalised. BuildHawk takes reasonable steps to ensure that any hosting
        provider meets appropriate data security standards.
      </p>

      <h2>5. Currency and regional separation</h2>
      <p>
        Australian project data is recorded and reported in AUD. New Zealand
        project data is recorded and reported in NZD. Data is never converted
        across currencies. Regional benchmarks are kept market-specific and are
        not combined across currency zones.
      </p>

      <h2>6. Data access and security</h2>
      <h3>6.1 Internal access</h3>
      <p>
        Access to Hawktress data within BuildHawk is role-based and determined
        by Nathan Holloway (Director). The CA has access to project and
        variation data for jobs under their management. Estimators have access
        to quote and actual cost data. No team member accesses data beyond their
        assigned role.
      </p>
      <h3>6.2 Subscriber access</h3>
      <p>
        Builders and trades access only their own data and anonymised market
        benchmarks. No subscriber can access another subscriber's project, cost,
        or variation data. Supplier profiles are visible to relevant builder
        subscribers as part of the supplier platform product only.
      </p>

      <h2>7. Data retention</h2>
      <p>
        BuildHawk retains subscriber data for the duration of the subscription
        and for seven years following its end, in accordance with Australian
        record-keeping obligations under the Corporations Act 2001 and the
        Income Tax Assessment Act 1997.
      </p>

      <h2>8. Disclosure</h2>
      <p>
        BuildHawk will not disclose subscriber data to any third party except
        where required by law, to platform infrastructure providers for service
        delivery purposes, or with the express written consent of the
        subscriber. BuildHawk does not sell, license, or commercially transfer
        subscriber data under any circumstances.
      </p>

      <h2>9. Privacy complaints</h2>
      <p>
        Complaints may be lodged in writing to{" "}
        <a href="mailto:services@buildhawk.com.au">services@buildhawk.com.au</a>.
        BuildHawk will acknowledge within 5 business days and respond
        substantively within 30 days. Unresolved complaints may be escalated to
        the Office of the Australian Information Commissioner (OAIC) at{" "}
        <a href="https://www.oaic.gov.au" target="_blank" rel="noopener noreferrer">
          www.oaic.gov.au
        </a>
        .
      </p>

      <h2>10. Policy updates</h2>
      <p>
        BuildHawk reserves the right to update this policy. Subscribers will be
        notified of material changes by email at least 14 days before changes
        take effect. Continued use of the platform following notification
        constitutes acceptance of the updated policy.
      </p>
    </LegalLayout>
  );
}
