import { neon } from "@neondatabase/serverless";
import { createHash, randomBytes } from "node:crypto";
import dotenv from "dotenv";
dotenv.config({ path: ".env.local" });
const sql = neon(process.env.DATABASE_URL);
const tid = `ten_h_${Date.now().toString(36)}`;
const uid = `usr_h_${Date.now().toString(36)}`;
const email = `h+${Date.now()}@t.l`;
await sql.query(`INSERT INTO tenants (id, slug, name, plan, status, trial_ends_at) VALUES ($1,$2,$3,'starter','trialing', now()+interval '14 days')`, [tid, `h-${Date.now().toString(36)}`, "HTest"]);
await sql.query(`INSERT INTO users (id, email, email_verified) VALUES ($1, $2, true)`, [uid, email]);
await sql.query(`INSERT INTO memberships (id, tenant_id, user_id, role) VALUES ($1,$2,$3,'owner')`, [`m_${Date.now().toString(36)}`, tid, uid]);
const raw = randomBytes(32).toString("base64url");
const hash = createHash("sha256").update(raw).digest("hex");
await sql.query(`INSERT INTO magic_links (id, token_hash, email, purpose, redirect, expires_at) VALUES ($1,$2,$3,'signin','/command-centre', now()+interval '30 min')`, [`l_${Date.now().toString(36)}`, hash, email]);
const v = await fetch(`https://www.buildhawk.com.au/api/command-centre/auth/verify?token=${encodeURIComponent(raw)}`, { redirect:"manual" });
const c = (v.headers.get("set-cookie")||"").match(/bh_session=([^;]+)/);
const cookie = `bh_session=${c[1]}`;
const r = await fetch(`https://www.buildhawk.com.au/command-centre`, { headers: { Cookie: cookie }, redirect:"manual" });
const html = await r.text();
const idx = html.indexOf("Autumn St");
if (idx >= 0) console.log("CONTEXT AROUND Autumn St:", html.substring(Math.max(0, idx-200), idx+200));
else console.log("Autumn St NOT present");
const idx2 = html.indexOf("HTest");
if (idx2 >= 0) console.log("\nCONTEXT AROUND HTest:", html.substring(Math.max(0, idx2-100), idx2+100));
await sql.query(`DELETE FROM tenants WHERE id = $1`, [tid]);
await sql.query(`DELETE FROM users WHERE id = $1`, [uid]);
